# Use an official Ubuntu image
FROM ubuntu:latest

# Set environment variables to non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Set proxy environment variables
ARG http_proxy
ARG https_proxy
ARG no_proxy
ENV http_proxy=${http_proxy}
ENV https_proxy=${https_proxy}
ENV no_proxy=${no_proxy}

# basic dependencies
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    wget \
    vim \
    gnupg2 \
    software-properties-common \
    build-essential \
    bash \
    jq \
    git \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory for the project
WORKDIR /workspace

# Start process
CMD ["/bin/bash"]
