name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Adjust to your primary branch
  pull_request:
    branches:
      - master  # Optionally run on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Tests in Docker
      run: |
        docker build -f Dockerfile.dev -t my-app:test .
        docker run --rm my-app:test ./scripts/run_tests.sh

    - name: Run Linting in Docker
      run: |
        docker build -f Dockerfile.dev -t my-app:lint .
        docker run --rm my-app:lint ./scripts/run_lint.sh

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Production Docker Image
      run: ./scripts/build_production.sh

