name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Ensure target directory exists
      run: |
        mkdir -p ${{ github.workspace }}/target

    - name: Set executable permissions for scripts
      run: |
        chmod +x ${{ github.workspace }}/scripts/*.sh

    - name: Build Docker Image
      run: |
        docker build -f ./docker/Dockerfile.dev -t my-app:latest .

    - name: Set up Docker volume for virtual environment
      run: |
        docker volume create venv_volume

    - name: Run Tests in Docker
      run: |
        docker run --rm \
          -v venv_volume:/venv \
          -v ${{ github.workspace }}/target:/target \
          -v ${{ github.workspace }}:/workspace:ro \
          my-app:latest /workspace/scripts/run_tests.sh

    - name: Run Linting in Docker
      run: |
        docker run --rm \
          -v venv_volume:/venv \
          -v ${{ github.workspace }}/target:/target \
          -v ${{ github.workspace }}:/workspace:ro \
          my-app:latest /workspace/scripts/run_lint.sh

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

# Production build has yet to be setup
#    - name: Build and Push Production Docker Image
#      run: ./scripts/build_production.sh

