name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your primary branch
  pull_request:
    branches:
      - main  # Optionally run on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv /workspace/venv
        source /workspace/venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Tests
      run: ./scripts/run_tests.sh

    - name: Run Linting
      run: ./scripts/run_lint.sh

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Production Docker Image
      run: ./scripts/build_production.sh

